// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4kzgdBrrQobjRz8p5W_40KWTs0LInfS8',
    appId: '1:974947367034:web:5f954a7d1ead5d63e4e3c3',
    messagingSenderId: '974947367034',
    projectId: 'cute-daily-planner',
    authDomain: 'cute-daily-planner.firebaseapp.com',
    storageBucket: 'cute-daily-planner.firebasestorage.app',
    measurementId: 'G-6G5Q14B1MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwXzxEAvMnllHUnaUAukj5qzG_02fXBTc',
    appId: '1:974947367034:android:344a2e4c8b9ab247e4e3c3',
    messagingSenderId: '974947367034',
    projectId: 'cute-daily-planner',
    storageBucket: 'cute-daily-planner.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzt-KCjp0wRohsvnQCjm8PH67_qCqqr8E',
    appId: '1:974947367034:ios:62f9948371a2f22ee4e3c3',
    messagingSenderId: '974947367034',
    projectId: 'cute-daily-planner',
    storageBucket: 'cute-daily-planner.firebasestorage.app',
    iosBundleId: 'com.example.cuteCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzt-KCjp0wRohsvnQCjm8PH67_qCqqr8E',
    appId: '1:974947367034:ios:62f9948371a2f22ee4e3c3',
    messagingSenderId: '974947367034',
    projectId: 'cute-daily-planner',
    storageBucket: 'cute-daily-planner.firebasestorage.app',
    iosBundleId: 'com.example.cuteCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4kzgdBrrQobjRz8p5W_40KWTs0LInfS8',
    appId: '1:974947367034:web:76ed5ef9e4418447e4e3c3',
    messagingSenderId: '974947367034',
    projectId: 'cute-daily-planner',
    authDomain: 'cute-daily-planner.firebaseapp.com',
    storageBucket: 'cute-daily-planner.firebasestorage.app',
    measurementId: 'G-LSGXRGB013',
  );

}